name: tokopedia
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.5

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  step_progress_indicator: ^1.0.2

flutter:
  assets:
    - 'assets/images/'
    - 'assets/images/menu/'
    - 'assets/images/detail/'
  uses-material-design: true
